export const FETCH_CITIES = 'FETCH_CITIES';
export const NEW_CITY = 'NEW_CITY';
export const FETCH_ITINERARIES = 'FETCH_ITINERARIES';
export const FETCH_ACTIVITIES = 'FETCH_ACTIVITIES';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';